### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by Achie72** [Achie72/switch-jump#5]
A better update could be used for much better presentation.
See example in [Neon Runner](https://github.com/Achie72/neon-runner)

Image could be grabbed from the [itch.io](https://achie.itch.io/switch-jump) site with:

`![alt text](link)` format

---

Moreover this update could contain blogs related to this project.

https://achie.itch.io/switch-jump/devlog/124432/devlog-1-map-system

**Comment by kisbg** [comment]
Hi Achie72 ! I created a pull request based on the issue :)
 #6
